# Generated by Django 5.2.9 on 2026-01-02 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_customer_default_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Plan name (e.g., Basic, Premium, Enterprise)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed plan description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly price', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of plan features')),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID', max_length=255, null=True)),
                ('stripe_product_id', models.CharField(blank=True, help_text='Stripe Product ID', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this plan available for purchase?')),
                ('display_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Subscription plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.subscriptionplan'),
        ),
    ]
