# Generated by Django 5.2.9 on 2026-01-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_subscriptionplan_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='FREE', max_length=10),
        ),
    ]
