# Generated by Django 5.2.9 on 2026-05-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_partition_wallettransaction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['created_at'], name='payments_wa_created_a3d6ca_idx'),
        ),
    ]
