# Generated by Django 5.2.9 on 2026-05-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_wallettransaction_payments_wa_created_a3d6ca_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_catalog_services',
            field=models.PositiveIntegerField(default=1, help_text='Max catalog services a provider can offer (0 = unlimited)'),
        ),
    ]
