# Generated by Django 5.2.9 on 2026-05-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_subscriptionplan_max_catalog_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='SILVER', max_length=10),
        ),
    ]
