# Generated by Django 5.2.9 on 2026-08-14 22:13

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_subscriptionplan_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_plan_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='store_transaction_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Apple original_transaction_id, Google purchaseToken, or Stripe subscription ID', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='apple_product_id',
            field=models.CharField(blank=True, help_text='Apple App Store product ID (must match App Store Connect exactly, e.g. nsapp_pro_monthly)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='google_product_id',
            field=models.CharField(blank=True, help_text='Google Play product ID (must match Play Console exactly, e.g. nsapp_pro_monthly)', max_length=255, null=True),
        ),
    ]
