# Generated by Django 5.2.9 on 2026-08-14 22:22

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_iap_store_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_product_id',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='store_transaction_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Apple original_transaction_id or Google purchaseToken', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='apple_product_id',
            field=models.CharField(blank=True, help_text='Apple App Store product ID (e.g. nsapp_pro_monthly)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='google_product_id',
            field=models.CharField(blank=True, help_text='Google Play product ID (e.g. nsapp_pro_monthly)', max_length=255, null=True),
        ),
    ]
