# Generated by Django 5.2.9 on 2026-08-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_stripe_subscription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_sandbox',
            field=models.BooleanField(default=False, help_text='True if this subscription was activated via a sandbox/test receipt'),
        ),
    ]
