"""
Django settings for ns_backend project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
env_path = BASE_DIR / '.env'
if env_path.exists():
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                try:
                    key, value = line.split('=', 1)
                    os.environ.setdefault(key.strip(), value.strip())
                except ValueError:
                    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^n&y0l=-ezgl0iwh0cw5*n18z5*--tfm(dbv))r-mjq%zs31@s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', 'api.neighborservice.com', 'www.neighborservice.com', 'neighborservice.com', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    'https://neighborservice.com',
    'https://www.neighborservice.com',
    'https://api.neighborservice.com',
    'http://localhost:3000',
    'http://localhost:8000',
    'http://localhost:8080',
]

# Application definition

INSTALLED_APPS = [
    'daphne',
    'unfold',  # Unfold admin
    'unfold.contrib.filters',  # Optional, if special filters are needed
    'unfold.contrib.forms',  # Optional, if special forms are needed
    'unfold.contrib.inlines',  # Optional, if special inlines are needed
    'unfold.contrib.import_export',  # Optional, if using django-import-export
    'unfold.contrib.guardian',  # Optional, if using django-guardian
    'unfold.contrib.simple_history',  # Optional, if using django-simple-history
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'channels',
    'encrypted_model_fields',

    # Local apps
    'accounts',
    'services',
    'interactions',
    'chat',
    'payments',
    'notifications',
    'moderation',
    'audit',
    'tracking',
    'consultations',
    'public_site',
]

# Agora Configuration
AGORA_APP_ID = os.environ.get('AGORA_APP_ID')
AGORA_APP_CERTIFICATE = os.environ.get('AGORA_APP_CERTIFICATE')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Proxy Settings for Absolute URIs
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

ROOT_URLCONF = 'ns_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'public_site.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'ns_backend.wsgi.application'
ASGI_APPLICATION = 'ns_backend.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(os.environ.get('REDIS_HOST', '127.0.0.1'), 6379)],
        },
    },
}


# Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.environ.get('REDIS_HOST', '127.0.0.1')}:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": "ns_cache"
    }
}

# Session Configuration to use Redis
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'nsapp'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'gentechco'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


# Email Configuration

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@neighborservice.com')

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Celery Configuration
REDIS_HOST = os.environ.get('REDIS_HOST', '127.0.0.1')
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', f'redis://{REDIS_HOST}:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', f'redis://{REDIS_HOST}:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_EAGER_PROPAGATES_EXCEPTIONS = True


CELERY_BEAT_SCHEDULE = {
    'check-upcoming-reminders-every-15-min': {
        'task': 'interactions.tasks.check_upcoming_appointments',
        'schedule': 900.0,  # 15 minutes
    },
    # Checkr fallback: re-sync stale pending background checks every hour
    'sync-pending-checkr-reports-hourly': {
        'task': 'moderation.tasks.sync_pending_checkr_reports',
        'schedule': 3600.0,  # 60 minutes
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/hour',
        'auth': '5/minute', # Custom rate for login/register
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Neighbor Service API',
    'DESCRIPTION': 'API documentation for Neighbor Service Application',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # 'OTHER_SETTINGS': '...',
}

# Simple JWT Configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Field Encryption Key
FIELD_ENCRYPTION_KEY = '0vziEohl8IILOzJbTBycGBuedQFlm6mCiWhlyeIHXDY='

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True # For development

# Unfold Admin Settings
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "NS Backend Admin",
    "SITE_HEADER": "NS Backend Configuration",
    "SITE_URL": "/",
    # "SITE_ICON": lambda request: static("icon.svg"),  # both modes, optimise for 32px height
    # "SITE_LOGO": lambda request: static("logo.svg"),  # both modes, optimise for 32px height
    "DASHBOARD_CALLBACK": "ns_backend.views.dashboard_callback",  # Optional: Callback for dashboard stats
    "COLORS": {
        "primary": {
            "50": "255 247 237",
            "100": "255 237 213",
            "200": "254 215 170",
            "300": "253 186 116",
            "400": "251 146 60",
            "500": "249 115 22",  # Brand Orange
            "600": "234 88 12",
            "700": "194 65 12",
            "800": "154 52 18",
            "900": "124 45 18",
            "950": "67 20 7",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False, # We are customizing it manually
        "navigation": [
            {
                "title": _("User Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                    {
                        "title": _("Profiles"),
                        "icon": "badge",
                        "link": reverse_lazy("admin:accounts_profile_changelist"),
                    },
                    {
                        "title": _("About Info"),
                        "icon": "info",
                        "link": reverse_lazy("admin:accounts_about_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("Service Catalog"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:services_category_changelist"),
                    },
                    {
                        "title": _("Catalog Services"),
                        "icon": "list_alt",
                        "link": reverse_lazy("admin:services_catalogservice_changelist"),
                    },
                ],
            },
            {
                "title": _("Service Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Service Requests"),
                        "icon": "assignment",
                        "link": reverse_lazy("admin:services_servicerequest_changelist"),
                    },
                    {
                        "title": _("Proposals"),
                        "icon": "description",
                        "link": reverse_lazy("admin:services_proposal_changelist"),
                    },
                    {
                        "title": _("Service Packages"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:services_servicepackage_changelist"),
                    },
                    {
                        "title": _("Portfolio Items"),
                        "icon": "photo_library",
                        "link": reverse_lazy("admin:accounts_portfolioitem_changelist"),
                    },
                ],
            },
            {
                "title": _("Interactions"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Appointments"),
                        "icon": "event",
                        "link": reverse_lazy("admin:interactions_appointment_changelist"),
                    },
                    {
                        "title": _("Reviews"),
                        "icon": "star",
                        "link": reverse_lazy("admin:interactions_review_changelist"),
                    },
                    {
                        "title": _("Favorites"),
                        "icon": "favorite",
                        "link": reverse_lazy("admin:interactions_favorite_changelist"),
                    },
                    {
                        "title": _("Disputes"),
                        "icon": "gavel",
                        "link": reverse_lazy("admin:interactions_dispute_changelist"),
                    },
                ],
            },
            {
                "title": _("Finance"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Customers"),
                        "icon": "account_circle",
                        "link": reverse_lazy("admin:payments_customer_changelist"),
                    },
                    {
                        "title": _("Wallets"),
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:payments_wallet_changelist"),
                    },
                    {
                        "title": _("Transactions"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:payments_wallettransaction_changelist"),
                    },
                    {
                        "title": _("Payout Requests"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:payments_payoutrequest_changelist"),
                    },
                    {
                        "title": _("Subscriptions"),
                        "icon": "card_membership",
                        "link": reverse_lazy("admin:payments_subscription_changelist"),
                    },
                    {
                        "title": _("Subscription Plans"),
                        "icon": "price_change",
                        "link": reverse_lazy("admin:payments_subscriptionplan_changelist"),
                    },
                ],
            },
            {
                "title": _("Communication"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Conversations"),
                        "icon": "chat",
                        "link": reverse_lazy("admin:chat_conversation_changelist"),
                    },
                    {
                        "title": _("Messages"),
                        "icon": "message",
                        "link": reverse_lazy("admin:chat_message_changelist"),
                    },
                    {
                        "title": _("Notifications"),
                        "icon": "notifications",
                        "link": reverse_lazy("admin:notifications_notification_changelist"),
                    },
                ],
            },
            {
                "title": _("Moderation"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Reports"),
                        "icon": "report",
                        "link": reverse_lazy("admin:moderation_report_changelist"),
                    },
                    {
                        "title": _("Provider Verifications"),
                        "icon": "verified_user",
                        "link": reverse_lazy("admin:moderation_providerverification_changelist"),
                    },
                    {
                        "title": _("Background Checks"),
                        "icon": "policy",
                        "link": reverse_lazy("admin:moderation_backgroundcheck_changelist"),
                    },
                    {
                        "title": _("Moderation Settings"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:moderation_moderationsetting_changelist"),
                    },
                ],
            },
            {
                "title": _("System"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Audit Logs"),
                        "icon": "history",
                        "link": reverse_lazy("admin:audit_auditlog_changelist"),
                    },
                ],
            },
            {
                "title": _("Public Site"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Hero Sections"),
                        "icon": "view_day",
                        "link": reverse_lazy("admin:public_site_herosection_changelist"),
                    },
                    {
                        "title": _("Features"),
                        "icon": "featured_play_list",
                        "link": reverse_lazy("admin:public_site_feature_changelist"),
                    },
                    {
                        "title": _("Testimonials"),
                        "icon": "format_quote",
                        "link": reverse_lazy("admin:public_site_testimonial_changelist"),
                    },
                    {
                        "title": _("FAQs"),
                        "icon": "question_answer",
                        "link": reverse_lazy("admin:public_site_faq_changelist"),
                    },
                    {
                        "title": _("About Content"),
                        "icon": "info",
                        "link": reverse_lazy("admin:public_site_aboutcontent_changelist"),
                    },
                    {
                        "title": _("How It Works"),
                        "icon": "linear_scale",
                        "link": reverse_lazy("admin:public_site_howitworksstep_changelist"),
                    },
                    {
                        "title": _("Site Stats"),
                        "icon": "bar_chart",
                        "link": reverse_lazy("admin:public_site_sitestat_changelist"),
                    },
                    {
                        "title": _("Site Settings"),
                        "icon": "settings_applications",
                        "link": reverse_lazy("admin:public_site_sitesetting_changelist"),
                    },
                ],
            },
        ],
    },
}

# Stripe Configuration
STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET')

# Checkr Background Check Configuration
CHECKR_API_KEY = os.environ.get('CHECKR_API_KEY', '')
CHECKR_WEBHOOK_SECRET = os.environ.get('CHECKR_WEBHOOK_SECRET', '')
CHECKR_PACKAGE = os.environ.get('CHECKR_PACKAGE', 'tasker_standard')
CHECKR_BASE_URL = 'https://api.checkr.com'

# OpenAI Configuration
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')

# APNS Configuration (Native Apple Push)
APNS_KEY_ID = os.environ.get('APNS_KEY_ID', '')
APNS_TEAM_ID = os.environ.get('APNS_TEAM_ID', '')
APNS_BUNDLE_ID = os.environ.get('APNS_BUNDLE_ID', 'com.neighborservicesolutionsllc.nsapp')
APNS_KEY_PATH = os.environ.get('APNS_KEY_PATH', os.path.join(BASE_DIR, 'notifications', 'keys', 'apns.p8'))
APNS_USE_SANDBOX = os.environ.get('APNS_USE_SANDBOX', 'True') == 'True'
