# Generated by Django 5.2.9 on 2026-01-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_appointment_reminder_day_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_consultation',
            field=models.BooleanField(default=False),
        ),
    ]
