# Generated by Django 5.2.9 on 2026-01-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_appointment_consultation_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_funded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
