# Generated by Django 5.2.9 on 2026-01-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_appointment_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
