# Generated by Django 4.2.30 on 2026-04-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0009_appointment_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='secret_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
