# Generated by Django 4.2.30 on 2026-04-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0010_remove_appointment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
