# Generated by Django 4.2.30 on 2026-04-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0011_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='dispute_evidence/'),
        ),
    ]
