# Generated by Django 5.2.9 on 2026-01-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_catalogservice_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
