# Generated by Django 5.2.9 on 2026-01-02 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicerequest_scheduled_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='BASIC', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_time_days', models.PositiveIntegerField(default=1)),
                ('revisions', models.IntegerField(default=0)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.catalogservice')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('provider', 'catalog_service', 'tier')},
            },
        ),
    ]
