# Generated by Django 5.2.9 on 2026-01-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicepackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
