# Generated by Django 5.2.9 on 2026-01-08 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicerequest_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('request', 'provider')},
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['is_approved'], name='services_pr_is_appr_f05b07_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['created_at'], name='services_pr_created_ce33bb_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status'], name='services_se_status_9254ae_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['latitude', 'longitude'], name='services_se_latitud_87e148_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['created_at'], name='services_se_created_fe46d7_idx'),
        ),
    ]
