# Generated by Django 4.2.30 on 2026-05-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_servicepackage'),
        ('services', '0007_servicerequest_target_provider'),
    ]

    operations = [
    ]
