# Generated by Django 4.2.30 on 2026-05-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_merge_20260504_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_payment_mode',
            field=models.CharField(choices=[('IN_APP', 'In-App Payment'), ('ON_SITE', 'On-Site Cash/Other')], default='IN_APP', max_length=20),
        ),
    ]
