# Generated by Django 5.2.9 on 2026-05-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_servicerequest_preferred_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='OPEN', max_length=20),
        ),
    ]
