# Generated by Django 5.2.9 on 2026-05-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_servicerequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='catalog_service',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='catalog_service',
            field=models.ManyToManyField(blank=True, null=True, related_name='requests', to='services.catalogservice'),
        ),
    ]
