# Generated by Django 5.2.9 on 2026-05-23 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_servicerequest_catalog_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='catalog_service',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='catalog_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='services.catalogservice'),
        ),
    ]
