# Generated by Django 4.2.30 on 2026-04-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0002_aboutcontent_howitworksstep_sitesetting_sitestat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='background_check_payment_mode',
            field=models.CharField(choices=[('IN_APP_STRIPE', 'In-App Stripe Checkout'), ('NATIVE_CHECKR', 'Native Checkr Candidate-Paid')], default='IN_APP_STRIPE', help_text='Choose how providers pay for their background check.', max_length=20),
        ),
    ]
