# Generated by Django 4.2.30 on 2026-05-04 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0003_sitesetting_background_check_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='background_check_payment_mode',
        ),
    ]
