# Generated by Django 5.2.9 on 2026-07-01 10:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0004_remove_sitesetting_background_check_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('inquiry_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('issue_type', models.CharField(max_length=100)),
                ('booking_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('other_neighbor', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_service', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('expected_outcome', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('account', 'Account & login'), ('bookings', 'Bookings'), ('payments', 'Payments'), ('app', 'The app'), ('providers', 'Providers'), ('code', 'Security Code'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
