# Generated by Django 5.2.9 on 2026-01-01 21:23

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
