# Generated by Django 4.2.30 on 2026-04-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_calender_date_message_calender_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='calender_end_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='calender_start_date',
        ),
    ]
