# Generated by Django 5.2.9 on 2026-01-01 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_address_alter_profile_date_of_birth_and_more'),
        ('services', '0002_catalogservice_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='catalog_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='services.catalogservice'),
        ),
    ]
