# Generated by Django 5.2.9 on 2026-01-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
