# Generated by Django 5.2.9 on 2026-01-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_bio'),
        ('services', '0006_alter_proposal_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_identity_verified'], name='accounts_pr_is_iden_58a320_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['latitude', 'longitude'], name='accounts_pr_latitud_7dd98b_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['average_rating'], name='accounts_pr_average_30f2db_idx'),
        ),
    ]
