# Generated by Django 5.2.9 on 2026-01-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_is_identity_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='FREE', max_length=10),
        ),
    ]
