# Generated by Django 5.2.9 on 2026-01-09 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_portfolioitem_tags_profile_subscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_tier',
            field=models.CharField(choices=[('NONE', 'None'), ('FREE', 'Free'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='NONE', max_length=10),
        ),
        migrations.CreateModel(
            name='PerformanceBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon_type', models.CharField(max_length=50)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_badges', to='accounts.profile')),
            ],
        ),
    ]
