# Generated by Django 5.2.9 on 2026-01-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_subscription_tier_performancebadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='about',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
