# Generated by Django 4.2.30 on 2026-04-24 01:29

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_about_education_about_experience_years_and_more'),
    ]

    operations = [
        # Using RunSQL to safely add column only if it doesn't exist
        migrations.RunSQL(
            sql='ALTER TABLE accounts_profile ADD COLUMN IF NOT EXISTS preferred_payment_mode varchar(10) DEFAULT \'ON_SITE\' NOT NULL;',
            state_operations=[
                migrations.AddField(
                    model_name='profile',
                    name='preferred_payment_mode',
                    field=models.CharField(choices=[('IN_APP', 'In-App Payment'), ('ON_SITE', 'On-Site Payment')], default='ON_SITE', max_length=10),
                ),
            ]
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('TERMS', 'Terms & Conditions'), ('PRIVACY', 'Privacy Policy')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['doc_type', 'is_active', 'created_at'], name='accounts_le_doc_typ_ebcfee_idx')],
            },
        ),
    ]
