# Generated by Django 5.2.9 on 2026-05-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_is_online_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbor_score',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
