# Generated by Django 5.2.9 on 2026-05-23 23:53

import django.db.models.deletion
from django.db import migrations, models


def migrate_catalog_services(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    for profile in Profile.objects.filter(catalog_service__isnull=False):
        profile.catalog_services.add(profile.catalog_service)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_last_check_in_profile_level_and_more'),
        ('services', '0011_remove_servicerequest_catalog_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='catalog_services',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='services.catalogservice'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='catalog_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_old', to='services.catalogservice'),
        ),
        migrations.RunPython(migrate_catalog_services, migrations.RunPython.noop),
    ]
