# Generated by Django 5.2.9 on 2026-05-23 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_catalog_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='catalog_service',
        ),
    ]
