# Generated by Django 5.2.9 on 2026-05-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_profile_catalog_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_tier',
            field=models.CharField(choices=[('NONE', 'None'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='NONE', max_length=10),
        ),
    ]
