# Generated by Django 5.2.9 on 2026-08-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_profile_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_interval',
            field=models.CharField(choices=[('none', 'None'), ('month', 'Monthly'), ('year', 'Yearly')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
    ]
