# Generated by Django 4.2.30 on 2026-04-30 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0002_providerverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkr_candidate_id', models.CharField(blank=True, max_length=255, null=True)),
                ('checkr_report_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('checkr_invitation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('invitation_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('package', models.CharField(default='tasker_standard', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAR', 'Clear'), ('CONSIDER', 'Consider'), ('SUSPENDED', 'Suspended'), ('DISPUTE', 'Dispute'), ('CANCELED', 'Canceled')], db_index=True, default='PENDING', max_length=30)),
                ('adjudication', models.CharField(blank=True, choices=[('ENGAGED', 'Engaged'), ('PRE_ADVERSE_ACTION', 'Pre-Adverse Action'), ('ADVERSE_ACTION', 'Adverse Action')], max_length=30, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Background Check',
                'verbose_name_plural': 'Background Checks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status'], name='moderation__provide_ef42ca_idx')],
            },
        ),
    ]
