# Generated by Django 4.2.30 on 2026-04-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_checkr_background_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundcheck',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
