# Generated by Django 4.2.30 on 2026-04-30 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_backgroundcheck_payment_intent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('background_check_payment_mode', models.CharField(choices=[('IN_APP_STRIPE', 'In-App Stripe Checkout'), ('NATIVE_CHECKR', 'Native Checkr Candidate-Paid')], default='IN_APP_STRIPE', help_text='Choose how providers pay for their background check.', max_length=20)),
            ],
            options={
                'verbose_name': 'Moderation Setting',
                'verbose_name_plural': 'Moderation Settings',
            },
        ),
    ]
