# Generated by Django 4.2.30 on 2026-04-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_moderationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationsetting',
            name='background_check_fee',
            field=models.DecimalField(decimal_places=2, default=29.99, help_text='The fee charged to providers for the background check (used for In-App Stripe Checkout).', max_digits=6),
        ),
    ]
